[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src 'self' https://prod.spline.design; script-src 'self' https://unpkg.com/@splinetool/viewer@1.0.87/build/spline-viewer.js https://netlify-cdp-loader.netlify.app/netlify.js; style-src 'self' https://fonts.googleapis.com https://netlify-cdp-loader.netlify.app; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data:;"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy= "geolocation=(), microphone=(), camera=(), interest-cohort=()"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"