[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy ="default-src 'self' https://prod.spline.design;'self'; script-src 'self'; script-src 'self' https://unpkg.com/@splinetool/viewer@1.0.87/build/spline-viewer.js; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data:;"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy= "geolocation=(), microphone=(), camera=(), interest-cohort=()"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"