[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src 'self' https://my.spline.design https://prod.spline.design; 'self'; script-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data:;"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy= "geolocation=(), microphone=(), camera=(), interest-cohort=()"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"